version: 1.0.{build}
branches:
  only:
  - master
  - ci/all
  - ci/appveyor

environment:
  ASIOSDK: C:\projects\ASIOSDK2.3
  OWNCLOUDPASS:
    secure: WMAPpQn8AuyEvSENma5wNQhsEYAxz87oJhgxiLRvtXg=
  OWNCLOUDUSER:
    secure: hGxoNrHEyHNyt12RjZ9cOQ==
  image: Visual Studio 2015
  matrix:
    - platform: Win32
      PTHREAD: x86
      configuration: Release32
      COMPILER: "Visual Studio 14 2015"
    - platform: x64
      PTHREAD: x64
      configuration: Release
      COMPILER: "Visual Studio 14 2015 Win64"

install:
    - echo "submodule %APPVEYOR_BUILD_FOLDER%"
    - git submodule -q update --init --recursive
    - cd %APPVEYOR_BUILD_FOLDER%\third_party\
    - echo "start build of PTW32"
    ############
    - mkdir PthreadWin32
    - git clone -q https://github.com/GerHobbelt/pthread-win32.git PthreadWin32
    - cd PthreadWin32
    - echo "bit of magic from camomille (pierreguillot)"
    ############
    - sed -i 's/4820;4668;4255;/4820;4668;4255;4711;4100;4312;4127;4296;4456;4619;4310;4311;/' pthread_lib.2015.vcxproj
    - sed -i 's/MultiThreadedDLL/MultiThreaded/' pthread_lib.2015.vcxproj
    - sed -i 's/MultiThreadedDebugDLL/MultiThreadedDebug/' pthread_lib.2015.vcxproj
    - echo "truely building PTW32"
    ##############
    - msbuild pthread.2015.sln /t:pthread_lib /nologo /verbosity:quiet /p:Configuration=Release /p:Platform=%PLATFORM% /p:OutDir=lib/

    - echo "Copy pthread-win32 headers and library in pure-data directory"
    #############
    - set LIBPDROOT="%APPVEYOR_BUILD_FOLDER%\third_party\libpd"
    - copy pthread.h %LIBPDROOT%\pure-data\src\pthread.h
    - copy sched.h %LIBPDROOT%\pure-data\src\sched.h
    - copy semaphore.h %LIBPDROOT%\pure-data\src\semaphore.h
    - set PD_BUILD_DIR="%APPVEYOR_BUILD_FOLDER%\third_party\libpdBuild"
    - copy lib\pthread_lib.lib %PD_BUILD_DIR%\VisualStudio2015\pthread.lib
    - copy lib\pthread_lib.lib %PD_BUILD_DIR%\pthread.lib

    - echo "Compile libpd"
    #################
    - cd %PD_BUILD_DIR%\VisualStudio2015
    - cmake -G "%COMPILER%" ..
    - msbuild libpd.sln /t:libpdstatic /nologo /verbosity:quiet /p:Configuration=Release /p:Platform=%PLATFORM%

before_build:
    - cd C:\projects\lgml\third_party\rubberband
    - echo 'building rubberband'
    - msbuild C:\projects\lgml\third_party\rubberband\rubberband-library.sln /p:Configuration=Release /m:4
    - echo 'dowloading JUCE'
    - cd C:\projects\
    - curl https://codeload.github.com/WeAreROLI/JUCE/zip/master -o JUCE.zip
    - 7z x JUCE.zip -o"C:\projects" -y
    - copy C:\projects\JUCE-master C:\projects\JUCE
    - dir
    - dir JUCE
    - echo 'downloading ASIOSDK'
    - curl https://www.steinberg.net/sdk_downloads/asiosdk2.3.zip -o ASIO_SDK.zip
    - 7z x ASIO_SDK.zip -o"C:\projects" -y


# after_build:
#   cmd: 7z a %APPVEYOR_BUILD_FOLDER%\LGML_%PLATFORM%.zip %APPVEYOR_BUILD_FOLDER%\Builds\VisualStudio2015\%PLATFORM%\%CONFIGURATION%\App\*.exe

deploy_script:
  - pip install future requests
  - cmd: python %APPVEYOR_BUILD_FOLDER%\Scripts\buildScript.py --configure --os=windows --configuration=%CONFIGURATION% --arch=%PLATFORM%  --exportpath=%APPVEYOR_BUILD_FOLDER%
  - cmd: python %APPVEYOR_BUILD_FOLDER%\Scripts\buildScript.py --package --export

artifacts:
  - path: '*.zip'

build:
  project: Builds/VisualStudio2015/LGML.sln
  verbosity: minimal
  parallel: true